const albumsActionsTypes = {
  SET_ALBUMSLIST: 'SET_ALBUMSLIST',
  SET_ALBUMSLIST_IS_FETCHING: 'SET_ALBUMSLIST_IS_FETCHING',
  SET_ALBUMSLIST_CURRENT_PAGE: 'SET_ALBUMSLIST_CURRENT_PAGE',
  SET_ALBUMSLIST_FETCH_ERROR: 'SET_ALBUMSLIST_FETCH_ERROR',
};

export default albumsActionsTypes;
